//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultipleAuthentication.DatabaseContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoggingEntities1 : DbContext
    {
        public LoggingEntities1()
            : base("name=LoggingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NewsLetter> NewsLetters { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
    }
}
