//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultipleAuthentication.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsLetter
    {
        public string HeadLine { get; set; }
        public string NewsDescription { get; set; }
        public string ActualLink { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> Priority { get; set; }
        public int ID { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
